# Generated by Django 3.2.8 on 2021-11-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorModel',
            fields=[
                ('advisor_id', models.AutoField(primary_key=True, serialize=False)),
                ('AdvisorName', models.CharField(max_length=100, unique=True)),
                ('AdvisorPhotoUrl', models.URLField(max_length=255)),
            ],
        ),
    ]
